encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index_redirect, name="index_redirect"),
    path("wiki/", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("wiki/<str:title>/edit", views.edit, name="edit"),
    path("wiki/search/", views.search, name="search"),
    path("wiki/random/", views.random, name="random"),
    path("wiki/create/", views.create, name="create"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponseNotFound, HttpResponseRedirect
from django.urls import reverse
from django import forms
from . import util
from markdown2 import Markdown
from random import randint

md = Markdown()


class NewEntryForm(forms.Form):
    title = forms.CharField(max_length=30, label="Title")
    md_content = forms.CharField(widget=forms.Textarea, label="", min_length=10)


class EditEntryForm(forms.Form):
    md_content = forms.CharField(widget=forms.Textarea, label="", min_length=10)


def entry_exists(title):
    for entry in util.list_entries():
        if title.lower() == entry.lower():
            return True
    return False


def index_redirect(request):
    return HttpResponseRedirect(reverse("encyclopedia:index"))


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def entry(request, title):
    raw_content = util.get_entry(title)
    if not raw_content:
        return HttpResponseNotFound('<h1>Entry does not exist.</h1> <a href="/">Go Home </a>')
    html_content = md.convert(raw_content)
    return render(request, "encyclopedia/entry.html", {
        "title": title,
        "content": html_content
    })


def edit(request, title):
    if request.method == "POST":
        form = EditEntryForm(request.POST)
        if form.is_valid():
            util.save_entry(title, form.cleaned_data["md_content"])
            return HttpResponseRedirect(reverse("encyclopedia:entry", args=(title,)))
        else:
            return render(request, "encyclopedia/edit.html", {
                "title": title,
                "message": "Content of the page must be at least 10 characters.",
                "form": form
            })
    raw_content = util.get_entry(title)
    if not raw_content:
        raise HttpResponseNotFound('<h1>Entry does not exist.</h1> <a href="/">Go Home </a>')
    edit_form = EditEntryForm(initial={"md_content":raw_content})
    return render(request, "encyclopedia/edit.html", {
        "title": title,
        "form": edit_form
    })


def search(request):
    query = request.GET.get("q")
    if util.get_entry(query):
        return HttpResponseRedirect(reverse("encyclopedia:entry", args=(query,)))
    matching_entries = []
    for entry in util.list_entries():
        if query.lower() in entry.lower():
            matching_entries.append(entry)

    return render(request, "encyclopedia/search.html", {
        "query": query,
        "entries": matching_entries
    })


def create(request):
    if request.method == "POST":
        create_form = NewEntryForm(request.POST)
        if create_form.is_valid():
            title = create_form.cleaned_data["title"].capitalize()
            md_content = create_form.cleaned_data["md_content"]
            if not entry_exists(title):
                util.save_entry(title, md_content)
                return HttpResponseRedirect(reverse("encyclopedia:entry", args=(title,)))
            else:
                return render(request, "encyclopedia/create.html", {
                    "message": f"The entry '{title}' already exists",
                    "form": create_form
                })
        else:
            return render(request, "encyclopedia/create.html", {
                "message": f"Form is not valid, check the fields",
                "form": create_form
            })
    create_form = NewEntryForm()
    return render(request, "encyclopedia/create.html", {
        "form": create_form
    })


def random(request):
    entries = util.list_entries()
    K = randint(0, len(entries)-1)
    return HttpResponseRedirect(reverse("encyclopedia:entry", args=(entries[K],)))

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Wiki - Create Entry
{% endblock %}

{% block body %}
    <h1> Create a new entry </h1>
    <form action="{% url 'encyclopedia:create' %}" method="post">
        {% csrf_token %}
        {% if message %}
        <div class="alert alert-danger" role="alert">{{ message }}</div>
        {% endif %}
        <p><i>Need help to format your content? Check this
            <a href="https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax">Markdown Guide</a></i></p>
        {{ form.as_p }}
        <input type="Submit" value="Save">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Wiki Editor - {{ title }}
{% endblock %}

{% block body %}
    <h1> {{ title }} </h1>
    <form action="{% url 'encyclopedia:edit' title %}" method="post">
        {% csrf_token %}
        {% if message %}
        <div class="alert alert-danger" role="alert">{{ message }}</div>
        {% endif %}
         <p><i>Need help to format your content? Check this
            <a href="https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax">Markdown Guide</a></i></p>
        {{ form.as_p }}
        <input type="Submit" value="Save">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Wiki - {{ title }}
{% endblock %}

{% block body %}
<label class="mr-5" style="float:right"><a href="{% url 'encyclopedia:edit' title %}">Edit this entry</a></label>
    <h1> {{ title }}</h1>
    {{ content | safe }}
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
        <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{%url 'encyclopedia:search' %}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h4>Displaying {{ entries | length }} entries found for your search '{{ query }}'</h4>

    <ul>
        {% for entry in entries %}
        <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
        {% empty %}
        <li>No entries found.</li>
        {% endfor %}
    </ul>

{% endblock %}